version: '3.9'

services:
  bot:
    build: .
    container_name: hamon-bot
    env_file:
      - .env
    volumes:
      - ./bot.log:/app/logs/bot.log
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - bot-net
    command: python main.py

  redis:
    image: redis:7-alpine
    container_name: hamon-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - bot-net

volumes:
  redis-data:

networks:
  bot-net:
    driver: bridge
